# Generated by Django 2.2.13 on 2020-08-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='education',
            field=models.TextField(default=''),
        ),
    ]
