# Generated by Django 2.2.13 on 2020-08-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cv_tech_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='additional_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cv',
            name='work_exp',
            field=models.TextField(blank=True, default=''),
        ),
    ]
