# Generated by Django 2.2.13 on 2020-08-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200831_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='work_exp',
            new_name='work_experience',
        ),
    ]
